### PR TITLE
Include bash scripts in the docker container

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
To simplify container environments we publish all scripts stored under `scripts` folder to the docker image. It will make k8s deployment easier. For extra scripts users can mount volume at runtime or they can rebuild their own image with additional scripts.

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-3977

### CODE REVIEW

**Review by phoinixgrr — APPROVED** [review]
It would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool. 

Ideally updating a k8s configmap, sends a signal for the application to reload configuration (such as argo-cd, and prometheus do) .

Ideally app configuration should be decoupled from the actual app. 

But since we want to ship this fast, and get some first reactions, it should be ok revisiting this in the future 👍

**Comment by pfltdv** [comment]
> would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool.

Do we need something else this documentation  and configuration yaml ?
https://github.com/mattermost/ops-tool/tree/main/doc , https://github.com/mattermost/ops-tool/blob/main/config/config.sample.yaml.

**Comment by pfltdv** [comment]
> It would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool.
> 
> Ideally updating a k8s configmap, sends a signal for the application to reload configuration (such as argo-cd, and prometheus do) .
> 
> Ideally app configuration should be decoupled from the actual app.
> 
> But since we want to ship this fast, and get some first reactions, it should be ok revisiting this in the future +1

If you are mentioning putting scripts into configuration files we have a ticket for that. https://github.com/mattermost/ops-tool/issues/23

**Comment by phoinixgrr** [comment]
> > would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool.
> 
> Do we need something else other than configuration documentation and configuration yaml ? https://github.com/mattermost/ops-tool/tree/main/doc , https://github.com/mattermost/ops-tool/blob/main/config/config.sample.yaml.

Script could be part of the yaml configuration. 
For example gitlab config: 
```
test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
```

**Comment by pfltdv** [comment]
> > > would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool.
> > 
> > 
> > Do we need something else other than configuration documentation and configuration yaml ? https://github.com/mattermost/ops-tool/tree/main/doc , https://github.com/mattermost/ops-tool/blob/main/config/config.sample.yaml.
> 
> Script could be part of the yaml configuration. For example gitlab config:
> 
> ```
> test-job2:
>   stage: test
>   script:
>     - echo "This job tests something, but takes more time than test-job1."
>     - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
>     - echo "which simulates a test that runs 20 seconds longer than test-job1"
>     - sleep 20
> ```

Relateed ticket https://github.com/mattermost/ops-tool/issues/23

**Comment by phoinixgrr** [comment]
> > It would be nice if we could describe the whole user configuration containing scripts via a data serialization language such as yaml, to be parsed at runtime by the ops-tool.
> > Ideally updating a k8s configmap, sends a signal for the application to reload configuration (such as argo-cd, and prometheus do) .
> > Ideally app configuration should be decoupled from the actual app.
> > But since we want to ship this fast, and get some first reactions, it should be ok revisiting this in the future +1
> 
> If you are mentioning putting scripts into configuration files we have a ticket for that. #23

Nice 👍 
Yes, We are burning configuration into the container, which is considered an anti-pattern.

**Pull request merged**
